[package]
name = "rust_nmea"
version = "1.0.0"
authors = ["Ahmetcan Aksu ahmetcanaksu@behemehal.net"]
edition = "2021"
description = "NMEA (0183) parser and information library for Rust. "
keywords = ["robotics", "ublox", "gps", "nmea", "gpio"]
categories = ["science::robotics"]

[dependencies]